import cv2

CAM_WINDOW = 'camera'
CAM_ID = 0
CAM_WIDTH = 960
CAM_HEIGHT = 540

CAP_WINDOW = 'capture'
CAP_WIDTH = 960
CAP_HEIGHT = 540

RES_WINDOW = 'result'
RES_WIDTH = 960
RES_HEIGHT = 540

LEG_WIDTH = 200
PALETTE_SIZE = 20
PALETTE_SPACING = 5

KEY_LIVE = 'l'
KEY_CAPTURE = 'c'
KEY_OPEN = 'o'
KEY_EXPORT = 'e'
KEY_FILL = 'f'
KEY_PROCESS = 'p'
KEY_SAVE = 's'
KEY_TEST = 't'
KEY_QUIT = 'q'

EVENT_CAMERA_SEGMENT = 0
EVENT_SEGMENT        = 1
EVENT_RESULT         = 2
EVENT_ACCURACY       = 3

COMMAND_STOP     = 0
COMMAND_SEGMENT  = 1
COMMAND_PROCESS  = 2
COMMAND_ACCURACY = 3

MODE = 'momentum' # avg, momentum, or just standard learning

STEP_SIZE = 10.0
STEP_EPSILON = 0.01
DELTA_CLIP = 5.0
ITERATIONS = 50

MOMENTUM_GAMMA = 0.1

AVG_WEIGHT = 0.1
